### ISSUE TITLE
Error con algunos appelidos

### ISSUE THREAD

**Issue by marcandre** [resuelve/rfc_facil#9]
```elixir
RfcFacil.for_natural_person("Lucero", "Ann", "Perez", "1972-01-01")
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a bitstring

    :erlang.bit_size(nil)
    (rfc_facil 0.1.3) lib/natural_person.ex:245: RfcFacil.NaturalPerson._name_part/3
    (rfc_facil 0.1.3) lib/natural_person.ex:187: RfcFacil.NaturalPerson.calculate/4
```

**Comment by marcandre** [comment]
("Ann" no tiene ningun vocal despues de la primera lettra)
